experimentName: NNI Tunner 
searchSpaceFile: search_space.json
trialCommand: python model_causal_reg.py
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 1
maxExperimentDuration: 96h
maxTrialNumber: 1600
tuner:
  name: GridSearch
trainingService:
  platform: local
  useActiveGpu: True